apiVersion: v1
kind: Service
metadata:
  name: dev-app-svc
  namespace: example-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dev-app
  type: ClusterIP
