
namespace: staging
dev_app:

  container_image: thangsu/devops-lab
  tag: staging-25c3606
  pullPolicy: IfNotPresent 

  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
      
  service:
    type: ClusterIP
    port: 8080
    target-port: 8080
  pull_secrets:
    name: registry-secret

ingress:
  domain: dev-app.kameyoko.online

mysql: 
  password: dGhhbmcyazMwMDM=

rabbitmq: 
  password: dGhhbmcyazMwMDM=