apiVersion: v1
kind: Service
metadata:
  name: dev-app-svc
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dev-app
  type: ClusterIP
