apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app
  labels: 
    app: dev-app
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-app
        image: "{{.Values.dev_app.container_image}}:{{.Values.dev_app.tag}}"
        ports: 
        - name: dev-app
          containerPort: 8080
      imagePullSecrets: 
      - name: {{.Values.dev_app.pull_secrets.name}}
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup dev-mysql-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup dev-memcached-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
