apiVersion: v1
kind: Service
metadata:
  name: dev-memcached-svc
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: 11211
    targetPort: dev-memcached-port
    protocol: TCP
  selector:
    app: dev-memcached
  type: ClusterIP
