apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-rabbitmq
  labels:
    app: dev-rabbitmq
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: dev-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-rabbitmq
    spec:
      containers:
      - name: dev-rabbitmq
        image: rabbitmq
        ports:
        - name: dev-rb-port
          containerPort: 5672
        env: 
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
             secretKeyRef:
               name: {{.Values.dev_app.pass_secret}}
               key: rmq-pass
         - name: RABBITMQ_DEFAULT_USER
           value: "guest"

