apiVersion: v1
kind: Service
metadata:
  name: dev-rabbitmq-svc
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: 5672
    targetPort: dev-rb-port
    protocol: TCP
  selector:
    app: dev-rabbitmq
  type: ClusterIP
